Update CI GitHub Action to run parallel checks

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,6 +5,7 @@ on:
     branches:
       - master
       - develop
+      - Reduce-Workflow-Time
 
     tags:
       - '*'
@@ -82,7 +83,7 @@ jobs:
   # ----------------------------------------------------------------------
   # R CHECK
   # ----------------------------------------------------------------------
-  check:
+  check_base:
     if: github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/build')
     runs-on: ubuntu-latest
 
@@ -131,7 +132,121 @@ jobs:
 
     # run PEcAn checks
     - name: check
-      run: make -j1 check
+      run: make -j1 -f Makefile.base check
+      env:
+        REBUILD_DOCS: "FALSE"
+        RUN_TESTS: "FALSE"
+
+    - name: check for out-of-date files
+      uses: infotroph/tree-is-clean@v1
+  
+  check_modules:
+    if: github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/build')
+    runs-on: ubuntu-latest
+
+    strategy:
+      fail-fast: false
+      matrix:
+        R:
+          - "4.0"
+          - "4.1"
+
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      _R_CHECK_LENGTH_1_CONDITION_: true
+      _R_CHECK_LENGTH_1_LOGIC2_: true
+      # Avoid compilation check warnings that come from the system Makevars
+      # See https://stat.ethz.ch/pipermail/r-package-devel/2019q2/003898.html
+      _R_CHECK_COMPILATION_FLAGS_KNOWN_: -Wformat -Werror=format-security -Wdate-time
+      # Keep R checks from trying to consult the very flaky worldclockapi.com
+      _R_CHECK_SYSTEM_CLOCK_: 0
+
+    container: 
+      image: pecan/depends:R${{ matrix.R }}
+
+    steps:
+    # checkout source code
+    - name: work around https://github.com/actions/checkout/issues/766
+      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
+    - uses: actions/checkout@v3
+      with:
+        set-safe-directory: false
+
+    # Forbid spaces in names. Yes, *we* know it's not 1980 anymore, but Make doesn't.
+    - name: check for filenames that would confuse Make
+      run: |
+        SPACENAMES=`find . -name '* *'`
+        if [ -n "$SPACENAMES" ]; then
+          echo "::error file=${SPACENAMES}::Spaces in filename(s): ${SPACENAMES}. Please rename these files by converting spaces to underscores."
+          exit 1
+        fi
+
+    # install additional tools needed
+    - name: install utils
+      run: apt-get update && apt-get install -y postgresql-client qpdf
+    - name: install new dependencies
+      run: Rscript scripts/generate_dependencies.R && Rscript docker/depends/pecan.depends.R
+
+    # run PEcAn checks
+    - name: check
+      run: make -f Makefile.module check
+      env:
+        REBUILD_DOCS: "FALSE"
+        RUN_TESTS: "FALSE"
+
+    - name: check for out-of-date files
+      uses: infotroph/tree-is-clean@v1
+
+  check_models:
+    if: github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/build')
+    runs-on: ubuntu-latest
+
+    strategy:
+      fail-fast: false
+      matrix:
+        R:
+          - "4.0"
+          - "4.1"
+
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      _R_CHECK_LENGTH_1_CONDITION_: true
+      _R_CHECK_LENGTH_1_LOGIC2_: true
+      # Avoid compilation check warnings that come from the system Makevars
+      # See https://stat.ethz.ch/pipermail/r-package-devel/2019q2/003898.html
+      _R_CHECK_COMPILATION_FLAGS_KNOWN_: -Wformat -Werror=format-security -Wdate-time
+      # Keep R checks from trying to consult the very flaky worldclockapi.com
+      _R_CHECK_SYSTEM_CLOCK_: 0
+
+    container: 
+      image: pecan/depends:R${{ matrix.R }}
+
+    steps:
+    # checkout source code
+    - name: work around https://github.com/actions/checkout/issues/766
+      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
+    - uses: actions/checkout@v3
+      with:
+        set-safe-directory: false
+
+    # Forbid spaces in names. Yes, *we* know it's not 1980 anymore, but Make doesn't.
+    - name: check for filenames that would confuse Make
+      run: |
+        SPACENAMES=`find . -name '* *'`
+        if [ -n "$SPACENAMES" ]; then
+          echo "::error file=${SPACENAMES}::Spaces in filename(s): ${SPACENAMES}. Please rename these files by converting spaces to underscores."
+          exit 1
+        fi
+
+    # install additional tools needed
+    - name: install utils
+      run: apt-get update && apt-get install -y postgresql-client qpdf
+    - name: install new dependencies
+      run: Rscript scripts/generate_dependencies.R && Rscript docker/depends/pecan.depends.R
+
+    # run PEcAn checks
+    - name: check
+      run: make -j1 -f Makefile.model check
       env:
         REBUILD_DOCS: "FALSE"
         RUN_TESTS: "FALSE"
